services:
  - type: web
    name: campus-bridge
    runtime: node
    nodeVersion: 18.x  # Explicitly requires Node 18
    buildCommand: |
      echo "==== BUILD STARTED ===="
      echo "Node: $(node -v)"
      echo "NPM: $(npm -v)"
      
      echo "🛠️ Building frontend..."
      cd frontend && npm ci --no-audit && npm run build
      
      echo "🔧 Installing backend (production only)..."
      cd ../backend && npm ci --no-audit --omit=dev
      echo "✔️ Backend dependencies installed"
      ls node_modules/express  # Verify critical package
    startCommand: |
      echo "==== STARTING SERVER ===="
      node -e "console.log('Express path:', require.resolve('express'))"
      node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000  # Must match server.js
      - key: VITE_API_BASE_URL
        value: https://campus-bridge.onrender.com
      - key: MONGODB_URI
        value: mongodb+srv://Aayush:aayush123@campusbridge-cluster.4itih3l.mongodb.net/campusbridge?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health
    autoDeploy: true