services:
  - type: web
    name: campus-bridge
    runtime: node
    nodeVersion: 18.x
    buildCommand: |
      echo "===== ATOMIC DEPENDENCY INSTALL ====="
      echo "Node $(node -v) | NPM $(npm -v)"
      
      # Nuclear option - fresh install
      cd backend
      rm -rf node_modules package-lock.json .npmrc
      echo "legacy-peer-deps=true" > .npmrc
      echo "strict-peer-deps=false" >> .npmrc
      
      npm install --production=false --no-audit --force
      echo "✅ Dependency Tree:"
      npm ls express --depth=1
      
      # Verify critical paths
      echo "🔍 Module Verification:"
      ls -la node_modules/express
      node -e "console.log('Express:', require.resolve('express'))"
      
      cd ../frontend
      npm install
      npm run build
    startCommand: |
      cd backend
      export NODE_PATH=./node_modules
      node -e "console.log('Final Express Path:', require.resolve('express'))"
      node server.js
    envVars:
      - key: NODE_PATH
        value: ./backend/node_modules
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000